// Lowpoint offline support. The app shell is precached as one versioned set and served cache-first, so old
// and new files never mix. vendor/ (MediaPipe wasm) and models/ are cached on first use in a separate,
// unversioned cache (cache-first). data/ and media/ (the Mac's local build) and the GitHub API are untouched.
// VERSION is generated by `node scripts/bump-sw.mjs` — rerun it whenever a listed file changes.
const VERSION = "ae3ed3bf36d8";
const CACHE = "lowpoint-" + VERSION;
const ASSETS = "lowpoint-assets-v1";
const FILES = [
  "./", "index.html", "style.css", "app.js", "manifest.webmanifest",
  "js/library.js", "js/lpcodec.js", "js/idb.js", "js/analyzer.js", "js/pose.js",
  "icons/favicon-32.png", "icons/icon-180.png", "icons/icon-192.png", "icons/icon-512.png",
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(cache => Promise.all(FILES.map(async f => {
    const res = await fetch(new Request(f + (f.includes("?") ? "&" : "?") + "v=" + VERSION, { cache: "reload" }));
    if (!res.ok) throw new Error(`precache failed for ${f}: ${res.status}`);
    await cache.put(f, res);
  }))));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE && k !== ASSETS).map(k => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", e => {
  const url = new URL(e.request.url);
  if (e.request.method !== "GET" || url.origin !== location.origin) return;
  const scope = new URL(self.registration.scope);
  const rel = url.pathname.startsWith(scope.pathname) ? url.pathname.slice(scope.pathname.length) : url.pathname;
  if (/^(data|media)\//.test(rel)) return; // local build only: always from the network
  if (/^(vendor|models)\//.test(rel)) {
    e.respondWith(caches.open(ASSETS).then(async cache => {
      const hit = await cache.match(e.request, { ignoreSearch: true });
      if (hit) return hit;
      const res = await fetch(e.request);
      if (res.ok && res.status === 200) cache.put(e.request, res.clone()).catch(() => {});
      return res;
    }));
    return;
  }
  e.respondWith(caches.open(CACHE).then(async cache => {
    const cached = await cache.match(e.request, { ignoreSearch: true });
    if (cached) return cached;
    try {
      return await fetch(e.request);
    } catch (err) {
      if (e.request.mode === "navigate") {
        const shell = await cache.match("./");
        if (shell) return shell;
      }
      throw err;
    }
  }));
});
